apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - changes:
        - go:
            owner:
              - jenkins-x-plugins
            package: github.com/jenkins-x/jx-helpers
            upgradePackages:
              include:
                - "github.com/jenkins-x/jx-helpers"
